#region Using
using Mod.CookieConsent.Models;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Handlers;
using Orchard.Localization;
#endregion

// This code was generated by Orchardizer

namespace Mod.CookieConsent.Handlers {
    public class CookieConsentSettingsPartHandler : ContentHandler {
        public CookieConsentSettingsPartHandler() {
            Filters.Add(new ActivatingFilter<CookieConsentSettingsPart>("Site"));
            T = NullLocalizer.Instance;
        }

        #region Properties
        public Localizer T { get; set; }
        #endregion

        #region Methods
        protected override void GetItemMetadata(GetContentItemMetadataContext context) {
            if (context.ContentItem.ContentType != "Site") {
                return;
            }
            base.GetItemMetadata(context);
            context.Metadata.EditorGroupInfo.Add(new GroupInfo(T(Constants.AdminMenuName)) {
                Position = "1"
            });
        }
        #endregion
    }
}
