using Orchard.ContentManagement.Handlers;
using Orchard.Data;
using Orchard.ContentManagement;
using Orchard.Localization;
using Mod.CookieConsent.Models;

// This code was generated by Orchardizer

namespace Mod.CookieConsent.Handlers {
    public class CookieConsentSettingsPartHandler : ContentHandler {
        public CookieConsentSettingsPartHandler() {
            Filters.Add(new ActivatingFilter<CookieConsentSettingsPart>("Site"));	
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }
        protected override void GetItemMetadata(GetContentItemMetadataContext context) {
            if (context.ContentItem.ContentType != "Site")
                return;
            base.GetItemMetadata(context);
            context.Metadata.EditorGroupInfo.Add(new GroupInfo(T("Cookie Consent")));
        }
    }
}